version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase
    versions:
    - 8.3.1
    - 8.3.2
    - 8.3.3
    - 8.4.0
    - 8.4.1
  - dependency-name: css-loader
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: eslint
    versions:
    - 5.16.0
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.2
  - dependency-name: react-lazyload
    versions:
    - 3.1.0
    - 3.1.1
    - 3.2.0
  - dependency-name: react-hot-loader
    versions:
    - 4.13.0
  - dependency-name: redux
    versions:
    - 4.0.5
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: yargs-parser
    versions:
    - 5.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: urijs
    versions:
    - 1.19.5
    - 1.19.6
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: file-loader
    versions:
    - 6.2.0
  - dependency-name: style-loader
    versions:
    - 2.0.0
  - dependency-name: url-loader
    versions:
    - 4.1.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: react-router
    versions:
    - 5.2.0
